### ISSUE TITLE
Create project card for OSA Project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [OpenSourceAutomations/OSA-Website#2]
### Overview
Provide collateral for the hackforla.org website

### Action Items
- [ ]   Gather items
  - [ ]  600 x 400 image
     - [ ]  Alt image text
  - [ ]  Name of project
  - [ ]  A blurb about the project
  - [ ]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [ ]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [ ]  What you are looking for skills wise
  - [ ]  Status: Active
- [ ]   Add project card 

### Resources/Instructions
See project cards on the hackforla.org website

**Comment by ExperimentsInHonesty** [comment]
``` 
identification: '67671778'
title: Open Source Automations
description: Hack for LA seeks to reduce repetitive work in our open source projects and for the open source community.  This project will be both a showcase for the automations and/or microservices that we develop, but also a convenient home for those automations, so that they can be found, forked, and contributed to easily.
image: /assets/images/projects/opensourceautomations.png
alt: "Open Source logo with hackforla logo on the left edge of it."
image-hero: /assets/images/projects/opensourceautomations-hero.png
alt-hero: "Green gears with a red center on one"
# leadership: **[none defined yet]**
# - name: 
#    role: 
#    links:
#      slack: 
#      github: 
#    picture: 
links: 
   - name: Slack 
      url: https://hackforla.slack.com/archives/CV7QGL66B
   - name: GitHub
      url: https://github.com/OpenSourceAutomations
   - name: ReadMe
      url: https://github.com/OpenSourceAutomations/OSA-Website/blob/master/README.md
looking:
   - category: Developer
      skill: Anyone who wants to write open source automations
   - category: Developer
      skill: API writers
   - category: Developer
      skill: API integrators
technologies: 
  - GitHub Pages
  - Jekyll
location:
   - Remote
# partner: N/A
status: Active
```
![opensourceautomations-lg](https://user-images.githubusercontent.com/37763229/86290891-0e2b3f00-bba3-11ea-9bbf-2c556fa9324b.png)
![gears-green-red](https://user-images.githubusercontent.com/37763229/86310724-932e4c80-bbd3-11ea-8001-b39cc1f2aae9.png)
